### ISSUE TITLE
NullPointerException for MediaType.getSchema()

### ISSUE THREAD

**Issue by 8luebottle** [Endava/cats#14]
I'm facing a `NullPointerException` issue.

The command that I ran was:
`./cats.jar --contract=openapi.yaml --server=https://subdomain.domain-name --paths=/v1/endpoint --headers=headers.yaml`

### Result Info
```shell
[********* ][*****] ● note     Proxy configuration to be used: DIRECT
[********* ][*****] ▶ start    Starting CATS, version 6.0.4, build-time 2021-07-23T06:05:54.116 UTC
[********* ][*****] ● note     Processing configuration...
[********* ][*****] ℹ info     No security custom Fuzzer file. SecurityFuzzer will be skipped!
[********* ][*****] ℹ info     No custom Fuzzer file. CustomFuzzer will be skipped!
[********* ][*****] ℹ info     No reference data file was supplied! Payloads supplied by Fuzzers will remain unchanged!
[********* ][*****] ▶ start    skipXXXForPath supplied arguments: []. Matching with registered fuzzers...
[********* ][*****] ☑ complete skipXXXForPath list after matching with registered fuzzers: []
[********* ][*****] ✖ error    Something went wrong while running CATS!
java.lang.NullPointerException: Cannot invoke "io.swagger.v3.oas.models.media.MediaType.getSchema()" because the return value of "io.swagger.v3.oas.models.media.Content.get(Object)" is null
	at com.endava.cats.CatsMain.addToSchemas(CatsMain.java:123)
	at com.endava.cats.CatsMain.lambda$getSchemas$0(CatsMain.java:111)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at com.endava.cats.CatsMain.getSchemas(CatsMain.java:111)
	at com.endava.cats.CatsMain.fuzzPath(CatsMain.java:355)
	at com.endava.cats.CatsMain.startFuzzing(CatsMain.java:175)
	at com.endava.cats.CatsMain.doLogic(CatsMain.java:166)
	at com.endava.cats.CatsMain.run(CatsMain.java:144)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
	at com.endava.cats.CatsMain.main(CatsMain.java:102)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```

How can I fix this issue?

**Comment by en-milie** [comment]
@8luebottle can you please post a sninpet from the OpenAPI contract?

**Comment by 8luebottle** [comment]
Hello @en-milie, is this what you are looking for?

```yaml
openapi: 3.0.0
info:
  title: OpenAPI Reference
  description: OpenAPI description
  version: 1.0.0
servers:
- url: "https://SUB_DOMAIN.domain"
  variables:
    SUB_DOMAIN:
      default: sub_domain
security:
- application:
  - read
  - write
tags:
- name: Folder
  description: Folder API
paths:
  /v1/folders/path/{var}:
    get:
      tags:
      - Folder
      summary: Get a list of folders
      description: ""
      operationId: getFolders
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                    success:
                      type: boolean
                      description: result
                      example: true
                    lists:
                      type: array
                      description: detail info
                      items:
                        $ref: '#/components/schemas/FolderList_lists'
      security:
      - AccessToken: []
    parameters:
    - name: var
      in: path
      description: folder seq
      required: true
      schema:
        type: string
        nullable: true
    - name: lang
      in: query
      description: ""
      schema:
        $ref: '#/components/schemas/Language'

components:
  schemas:
    Language:
      type: string
      description: ""
      enum:
      - eng
      - fra
      - spa
      default: eng
    FolderList:
      properties:
        success:
          type: boolean
          description: ""
          example: true
        lists:
          type: array
          description: detail info
          items:
            $ref: '#/components/schemas/FolderList_lists'

  securitySchemes:
    AccessToken:
      type: apiKey
      description: "Enter your Access Token in the format."
      name: access_token
      in: header
```

**Comment by en-milie** [comment]
Hi @8luebottle. Is this the exact content of the `openapi.yaml` file that you are supplying as argument? When I run on by box I get the following output: 
```
[********* ][*****] ● note     Proxy configuration to be used: DIRECT
[********* ][*****] ▶ start    Starting CATS, version 6.0.5-SNAPSHOT, build-time 2021-08-23T13:31:55.964 UTC
[********* ][*****] ● note     Processing configuration...
[********* ][*****] ℹ info     No security custom Fuzzer file. SecurityFuzzer will be skipped!
[********* ][*****] ℹ info     No custom Fuzzer file. CustomFuzzer will be skipped!
[********* ][*****] ℹ info     No reference data file was supplied! Payloads supplied by Fuzzers will remain unchanged!
[********* ][*****] ℹ info     No URL parameters supplied!
[********* ][*****] ▶ start    skipXXXForPath supplied arguments: []. Matching with registered fuzzers...
[********* ][*****] ☑ complete skipXXXForPath list after matching with registered fuzzers: []
[********* ][*****] ℹ info
[********* ][*****] ℹ info     Supplied arguments
[********* ][*****] ℹ info     contract: issue_14.yaml
[********* ][*****] ℹ info     server: https://subdomain.domain-name
[********* ][*****] ℹ info     maxRequestsPerMinute: empty
[********* ][*****] ℹ info     fuzzers: all
[********* ][*****] ℹ info     paths: /v1/endpoint
[********* ][*****] ℹ info     skipPaths: empty
[********* ][*****] ℹ info     excludedFuzzers: empty
[********* ][*****] ℹ info     skipXXXForPath: []
[********* ][*****] ℹ info     skipFields: empty
[********* ][*****] ℹ info     httpMethods: empty
[********* ][*****] ℹ info     checkHeaders: false
[********* ][*****] ℹ info     checkFields: false
[********* ][*****] ℹ info     checkHttp: false
[********* ][*****] ℹ info     checkContract: false
[********* ][*****] ℹ info     fieldsFuzzingStrategy: ONEBYONE
[********* ][*****] ℹ info     maxFieldsToRemove: empty
[********* ][*****] ℹ info     edgeSpacesStrategy: trimAndValidate
[********* ][*****] ℹ info     sanitizationStrategy: sanitizeAndValidate
[********* ][*****] ℹ info     useExamples: true
[********* ][*****] ℹ info     reportingLevel: info
[********* ][*****] ℹ info     log: empty
[********* ][*****] ℹ info     printExecutionStatistics: false
[********* ][*****] ℹ info     timestampReports: empty
[********* ][*****] ℹ info     reportFormat: htmlJs
[********* ][*****] ℹ info     urlParams: empty
[********* ][*****] ℹ info     headers: headers.yml
[********* ][*****] ℹ info     refData: empty
[********* ][*****] ℹ info     customFuzzerFile: empty
[********* ][*****] ℹ info     securityFuzzerFile: empty
[********* ][*****] ℹ info     proxyPort: 0
[********* ][*****] ℹ info     proxyHost: empty
[********* ][*****] ℹ info     sslKeystore: empty
[********* ][*****] ℹ info     sslKeystorePwd: empty
[********* ][*****] ℹ info     sslKeyPwd: empty
[********* ][*****] ℹ info     basicauth: empty
[********* ][*****] ☑ complete Finished parsing the contract in 116 ms
[********* ][*****] ≫ skipping Supplied path is not matching the contract /v1/endpoint
[********* ][*****] ≫ skipping Skipping path /v1/folders/path/{var}
[********* ][*****] ≫ skipping Skip printing time execution statistics. You can use --printExecutionStatistics to enable this feature!
[********* ][*****] ☑ complete CATS finished in 1146 ms. Total (excluding skipped) requests 0. ✔ Passed 0, ⚠ warnings: 0, ‼ errors: 0, ❯ skipped: 0. 
```

One other remark is that `/v1/endpoint` does not actually exist inside the OpenAPI contract file.

**Comment by 8luebottle** [comment]
@en-milie 
The original `openapi.yaml` file has a bunch of paths and examples.
Once I removed examples and components it works fine.

Looks like the exception belongs to the `requestBodies`

### Example of removal
```yaml
  examples:
    InputValueIsInvalid:
      description: ""
      value:
        success: false
        message: Input value is invalid.
    InvalidLogin:
      description: ""
      value:
        success: false
        message: Invalid login information
  requestBodies:
    CreateFolderRequest:
      content:
        multipart/form-data:
          schema:
            required:
            - name
            type: object
            properties:
              name:
                type: string
                description: ""
                example: NewFolder
```

FYFI: The yaml file has been generated by `swagger-codegen` command.

Thank you for your help.
