### ISSUE TITLE
java.lang.NullPointerException when run cats fuzz

### ISSUE THREAD

**Issue by duhang1996** [Endava/cats#140]
./cats fuzz -X GET -t "path1" https://petstore3.swagger.io/api/v3/pet/path1 --mc "2XX,5XX"                       
 
[][] ▶ Starting cats-12.0.0, build time 2024-08-28T16:58:59Z UTC, platform Mac OS X-12.0-aarch64 
 
================================================================================= FUZZING =================================================================================
java.lang.NullPointerException
	at com.endava.cats.report.TestCaseListener.notifySummaryObservers(TestCaseListener.java:331)
	at com.endava.cats.report.TestCaseListener_Subclass.notifySummaryObservers$$superforward(Unknown Source)
	at com.endava.cats.report.TestCaseListener_Subclass$$function$$19.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at com.endava.cats.aop.DryRunAspect.intercept(DryRunAspect.java:129)
	at com.endava.cats.aop.DryRunAspect_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.endava.cats.report.TestCaseListener_Subclass.notifySummaryObservers(Unknown Source)
	at com.endava.cats.report.TestCaseListener.beforeFuzz(TestCaseListener.java:141)
	at com.endava.cats.report.TestCaseListener_Subclass.beforeFuzz$$superforward(Unknown Source)
	at com.endava.cats.report.TestCaseListener_Subclass$$function$$14.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at com.endava.cats.aop.DryRunAspect.intercept(DryRunAspect.java:129)
	at com.endava.cats.aop.DryRunAspect_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.endava.cats.report.TestCaseListener_Subclass.beforeFuzz(Unknown Source)
	at com.endava.cats.report.TestCaseListener_ClientProxy.beforeFuzz(Unknown Source)
	at com.endava.cats.command.TemplateFuzzCommand.beforeFuzz(TemplateFuzzCommand.java:194)
	at com.endava.cats.command.TemplateFuzzCommand.run(TemplateFuzzCommand.java:145)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
	at picocli.CommandLine.execute(CommandLine.java:2174)
	at com.endava.cats.CatsMain.run(CatsMain.java:41)
	at com.endava.cats.CatsMain_ClientProxy.run(Unknown Source)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:140)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base@21.0.4/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)

**Comment by en-milie** [comment]
I've pushed a fix. It will be available in next release.
