### ISSUE TITLE
NullPointerException in PayloadGenerator.parseFromInnerSchema

### ISSUE THREAD

**Issue by jvert** [Endava/cats#44]
(swagger.json in the attached zip file)

./cats --debug --paths=/api/groopits/create  --contract=swagger.json --dryRun --server=http://example.com

`
java.lang.NullPointerException
        at com.endava.cats.model.generator.PayloadGenerator.parseFromInnerSchema(PayloadGenerator.java:360)
        at com.endava.cats.model.generator.PayloadGenerator.processSchemaProperties(PayloadGenerator.java:342)
        at com.endava.cats.model.generator.PayloadGenerator.resolveModelToExample(PayloadGenerator.java:318)
        at com.endava.cats.model.generator.PayloadGenerator.getExampleFromArraySchema(PayloadGenerator.java:274)
        at com.endava.cats.model.generator.PayloadGenerator.resolvePropertyToExample(PayloadGenerator.java:137)
        at com.endava.cats.model.generator.PayloadGenerator.parseFromInnerSchema(PayloadGenerator.java:364)
        at com.endava.cats.model.generator.PayloadGenerator.processSchemaProperties(PayloadGenerator.java:342)
        at com.endava.cats.model.generator.PayloadGenerator.resolveModelToExample(PayloadGenerator.java:318)
        at com.endava.cats.model.generator.PayloadGenerator.generate(PayloadGenerator.java:115)
        at com.endava.cats.factory.FuzzingDataFactory.generateSample(FuzzingDataFactory.java:307)
        at com.endava.cats.factory.FuzzingDataFactory.getResponsePayloads(FuzzingDataFactory.java:472)
        at com.endava.cats.factory.FuzzingDataFactory.getFuzzDataForHttpMethod(FuzzingDataFactory.java:187)
        at com.endava.cats.factory.FuzzingDataFactory.getFuzzDataForPost(FuzzingDataFactory.java:145)
        at com.endava.cats.factory.FuzzingDataFactory.fromPathItem(FuzzingDataFactory.java:76)
        at com.endava.cats.factory.FuzzingDataFactory_ClientProxy.fromPathItem(Unknown Source)
        at com.endava.cats.command.CatsCommand.fuzzPath(CatsCommand.java:198)
        at com.endava.cats.command.CatsCommand.startFuzzing(CatsCommand.java:137)
        at com.endava.cats.command.CatsCommand.doLogic(CatsCommand.java:121)
        at com.endava.cats.command.CatsCommand.run(CatsCommand.java:108)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at com.endava.cats.CatsMain.run(CatsMain.java:27)
        at com.endava.cats.CatsMain_ClientProxy.run(Unknown Source)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:124)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
`

[swagger.zip](https://github.com/Endava/cats/files/8903499/swagger.zip)

**Comment by en-milie** [comment]
Hi @jvert. Thank you for reporting this. Quite an interesting case of `anyOf/oneOf` without actually using it per se. Just curious, are the specs generated? Or more like contract-first?

**Comment by en-milie** [comment]
This should be fixed in the latest commit.

**Comment by en-milie** [comment]
This is now available in https://github.com/Endava/cats/releases/tag/cats-7.3.1
